### ISSUE TITLE
Bonding curve models

### ISSUE THREAD

**Issue by andrejus-notcat** [gluon-project/gluon-contracts#10]
1) If we're creating the new token and choose 'exponent 1' we get superlinear curve? 

2) If we're creating the new token and choose 'exponent 2' we get exponential curve? - quote from the article ''The problem is not necessarily the absolute price — especially since we can trade fractional tokens. The more significant problem is that the growth rate and gains accelerate as the number of tokens minted increases. You get a price that becomes more volatile with more speculative upside and downside as the project becomes more popular. This is possibly the worst speculative environment we could design for a token given the behaviour we’ve experienced in the cryptocurrency markets so far.''

3) What's the point of the linear curve if token price all time rise at the same pace? e.g. 10 token=10USD, 100 token=100USD, 1000 token=1000USD and etc. Token price is always the same. It means that YOu can mint/burn token at any time at the same price 1 token=1USD.

**Comment by oed** [comment]
1. No we get a linear one. Basically y = x

2. Here we get a superlinear curve. That is y = x^2. Exponentials are not supported by our code. They would look something like y = e^x.

3. That's not really how it works. if you have a linear curve the price to mint 10 tokens depends on how many tokens that already exists. You basically take the integral of y = x from the number of tokens that currently exists, to the number of tokens that will exist after you have minted yours. I understand that this isn't super simple. We could jump on a call to discuss if needed. It's easier to explain with visuals :)
