### ISSUE TITLE
MVP version of ERC223 + Bonding Curves smart contract

### ISSUE THREAD

**Issue by simonas-notcat** [gluon-project/gluon-contracts#2]
How to determine if token contract supports bonding curve methods (mint, burn, attachment)?

Do we need a separate method for that?

**Comment by oed** [comment]
You can just call `isCommunityToken` on the token factory.
https://github.com/gluon-project/gluon-contracts/blob/feature/bonding-curves/contracts/CommunityTokenFactory.sol#L11
