### ISSUE TITLE
Tokens (MMC token) with exponent=2 model

### ISSUE THREAD

**Issue by andrejus-notcat** [gluon-project/gluon-contracts#8]
Total supply | Worth of total supply in GLU | Price of each token | Difference in every second token price
-- | -- | -- | --
  |   |   |  
1 MMC | 0 GLU | 0 |  
  |   |   | 2
2 MMC | 2 GLU | 2 |  
  |   |   | 4
3 MMC | 8 GLU | 6 |  
  |   |   | **7**
4 MMC | 21 GLU | 13 |  
  |   |   | **7**
5 MMC | 41 GLU | 20 |  
  |   |   | 10
6 MMC | 71 GLU | 30 |  
  |   |   | **13**
7 MMC | 114 GLU | 43 |  
  |   |   | **13**
8 MMC | 170 GLU | 56 |  
  |   |   | 16
9 MMC | 242 GLU | 72 |  
  |   |   | 19
10 MMC | 333 GLU | 91 |  

1) There's no possibility to buy e.g. 2.2 or any other quantity with decimals. Let's say I have 17 GLU tokens so i can't buy neither fourth, neither fifth token. I think that we should allow users to buy/sell any amount of tokens even if it's 0.0001;

2) How come the first MMC token is for free? Even in bonding curve graph you can see that when 1MMC token is bought the the price moves above 0 in y axis;

3) If second token is bought it's price gets up to 2 GLU token - so with 1 GLU token user can't buy anything;

4) Why the difference in token prices are the same when customer wants to buy **fifth** token and **eighth** token?;

5) We have hypothesis that total suply of GLU token will rise and the price will rise as well so the standart ''exponent'' should be definately less than 2. As less the price will rice with the rise of the total supply the more users can do with the tokens.

**Comment by andrejus-notcat** [comment]
@oed

**Comment by oed** [comment]
@andrejus-notcat Thanks for this! Sorry that I've missed it until now! Need some time to digest.
